version: "3"
services:
  seata-server:
    image: seataio/seata-server:1.1.0
    container_name: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_IP=127.0.0.1 #seata-server启动的IP，用于向注册中心注册使用，默认使用容器IP可能无法与客户端通讯
      - SEATA_PORT=8091 #seata-server启动端口，默认8091