server:
  port: 8081

spring:
  application:
    name: at-multiple-datasource

  datasource:
    # dynamic-datasource-spring-boot-starter 动态数据源的配置，对应DynamicDataSourceProperties类
    dynamic:
      # 设置默认的数据源或者数据源组，默认值：master
      primary: order-ds
      # 是否启动对 seata 的集成
      seata: true
      datasource:
        # 订单 order 数据源配置
        order-ds:
          url: jdbc:mysql://127.0.0.1:3306/seata_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
        # 订单 pay 数据源配置
        amount-ds:
          url: jdbc:mysql://127.0.0.1:3306/seata_amount?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
        # 订单 storage 数据源配置
        storage-ds:
          url: jdbc:mysql://127.0.0.1:3306/seata_storage?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456

    # seata配置，对应SeataProperties类
    seata:
      # seata 应用编号，默认为${spring.datasource.name}
      application-id: ${spring.application.name}
      # Seata 事务组编号，用于TC集群名
      tx-service-group: ${spring.application.name}-group
      # 服务配置，对应ServiceProperties类
      service:
        # 虚拟组和分组的映射
        vgroup-mapping:
          at-multiple-datasource-group: default
        # 分组和Seata服务的映射
        grouplist:
          default: 127.0.0.1:8091