spring:
  datasource:
    url: jdbc:postgresql://192.168.248.4:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

logging:
  level:
    com.postgresql.demo.mc.mapper: DEBUG